---
title: "Research"
date-modified: today
output-dir: docs
---

## Tools & Infrastructure

### Geospatial

-   GNSS surveying system : Emlid 2

-   Ground based Thermal Infrared Imagerie

-   O2 Lite Lidar Slam Scanner

### Hydrological

-   Flowtracker 2

-   Hobo MX

-   Trail Camera

-   ICOS Water Isotope Analyzer

### Carbon sensing

-   Data loggers: Campbell Scientific

-   Oxygen: Mini-Do2T

-   CO2: Vaisala, C-sense and mini-sensors, in air (K33 sense air)

-   CH4: Pro-Oceanus, Solub-blue and mini sensors.

-   LGR: Ultraportable CO2 and CH4 analyzer

## Field Sites

<iframe src="https://www.google.com/maps/d/embed?mid=1XhQxU5bQlNBSGpYkAbjyCuK1aHFK2Rk&amp;ehbc=2E312F" width="640" height="480">

</iframe>

## Funded Projects

::::: grid
::: g-col-6
### Taking the pulse of 

Investigating how changing precipitation patterns affect watershed hydrology across Quebec.

**Funding:** NSERC Discovery Grant

**Duration:** 2023-2026

**Lead:** A.Campeau
:::

::: g-col-6
### Ruisseau sentinels: 

Developing geospatial tools to quantify ecosystem services in urban watersheds.

**Funding:** FRQ-new researcher

**Duration:** 2024-2027

**Lead:** A.Campeau
:::
:::::

::::: grid
::: g-col-6
### CONTAC \| the carbon observatory network of the aquatic and terrestrial connectivity

**Funding:** FCI leader

**Duration:** 2024-2026

**Lead:** A.Campeau
:::

::: g-col-6
:::
:::::

## 
